/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_stocks__stock_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/ohlcv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Ohlcv */
        get: operations["stock_ohlcv_stocks__stock_id__ohlcv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Holdings */
        get: operations["list_holdings_holdings_get"];
        put?: never;
        /** Create Holding */
        post: operations["create_holding_holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings/{holding_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Transaction */
        post: operations["add_transaction_holdings__holding_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Holding */
        delete: operations["delete_holding_holdings__holding_id__delete"];
        options?: never;
        head?: never;
        /** Patch Holding */
        patch: operations["patch_holding_holdings__holding_id__patch"];
        trace?: never;
    };
    "/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sectors */
        get: operations["list_sectors_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sectors/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector Detail */
        get: operations["sector_detail_sectors__sector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources Health */
        get: operations["sources_health_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Source
         * @description 設定頁[測試連線]：可先測再存（測通才存）。
         */
        post: operations["test_source_sources__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Pipeline
         * @description 手動重跑（設定頁 / 補跑）。背景執行，立即回 accepted。
         */
        post: operations["trigger_pipeline_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candle */
        Candle: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Volume */
            volume: number | null;
            /** Ma5 */
            ma5?: number | null;
            /** Ma20 */
            ma20?: number | null;
            /** Ma60 */
            ma60?: number | null;
            /** Kd K */
            kd_k?: number | null;
            /** Kd D */
            kd_d?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
        };
        /** ChipSummary */
        ChipSummary: {
            /** Date */
            date: string | null;
            /** Foreign Net */
            foreign_net: number | null;
            /** Trust Net */
            trust_net: number | null;
            /** Dealer Net */
            dealer_net: number | null;
            /** Total Net */
            total_net: number | null;
            /** Margin Balance */
            margin_balance: number | null;
            /** Short Balance */
            short_balance: number | null;
        };
        /** FundamentalSummary */
        FundamentalSummary: {
            /** Pe */
            pe?: number | null;
            /** Pb */
            pb?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Eps */
            eps?: number | null;
            /** Revenue Yoy */
            revenue_yoy?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingCreate */
        HoldingCreate: {
            /** Stock Id */
            stock_id: string;
            /** Track */
            track: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /** Fee */
            fee?: number | null;
            /** Stop Loss Override */
            stop_loss_override?: number | null;
            /** Trail Trigger Override */
            trail_trigger_override?: number | null;
            /** Trail Pullback Override */
            trail_pullback_override?: number | null;
            /** Note */
            note?: string | null;
        };
        /** HoldingItem */
        HoldingItem: {
            /** Id */
            id: number;
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Track */
            track: string;
            /** Status */
            status: string;
            /** Opened Date */
            opened_date: string | null;
            /** Closed Date */
            closed_date: string | null;
            /** Shares */
            shares: number;
            /** Avg Cost */
            avg_cost: number | null;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Market Value */
            market_value: number | null;
            /** Unrealized Pnl */
            unrealized_pnl: number | null;
            /** Return Pct */
            return_pct: number | null;
            /** Realized Pnl */
            realized_pnl: number | null;
            /** Light */
            light: string;
            /** Level */
            level: string;
            /** Signals */
            signals: string[];
            /** Hard Stop */
            hard_stop: number | null;
            /** Highest */
            highest: number | null;
            /** Drawdown Pct */
            drawdown_pct: number | null;
            /** Trail Active */
            trail_active: boolean;
            /** Stop Loss Override */
            stop_loss_override: number | null;
            /** Trail Trigger Override */
            trail_trigger_override: number | null;
            /** Trail Pullback Override */
            trail_pullback_override: number | null;
            /** Note */
            note: string | null;
            /** Transactions */
            transactions: components["schemas"]["TransactionDTO"][];
        };
        /** HoldingPatch */
        HoldingPatch: {
            /** Stop Loss Override */
            stop_loss_override?: number | null;
            /** Trail Trigger Override */
            trail_trigger_override?: number | null;
            /** Trail Pullback Override */
            trail_pullback_override?: number | null;
            /** Note */
            note?: string | null;
        };
        /** HoldingsResponse */
        HoldingsResponse: {
            /** Status */
            status: string;
            /** Items */
            items: components["schemas"]["HoldingItem"][];
            summary: components["schemas"]["HoldingsSummary"];
        };
        /** HoldingsSummary */
        HoldingsSummary: {
            /** Count */
            count: number;
            /** Total Market Value */
            total_market_value: number;
            /** Total Unrealized Pnl */
            total_unrealized_pnl: number;
            /** Total Return Pct */
            total_return_pct: number | null;
            /** Total Realized Pnl */
            total_realized_pnl: number;
        };
        /** OhlcvResponse */
        OhlcvResponse: {
            /** Stock Id */
            stock_id: string;
            /** Candles */
            candles: components["schemas"]["Candle"][];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Sector Name */
            sector_name: string | null;
            /** Track */
            track: string;
            /** Total Score */
            total_score: number | null;
            /** Sub Scores */
            sub_scores: {
                [key: string]: number;
            } | null;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Buy Low */
            buy_low: number | null;
            /** Buy High */
            buy_high: number | null;
            /** Stop Loss */
            stop_loss: number | null;
            /** Loss Pct */
            loss_pct: number | null;
            /** Reasons */
            reasons: string[] | null;
        };
        /** RecommendationList */
        RecommendationList: {
            /** Track */
            track: string;
            /** Date */
            date: string | null;
            /** Threshold */
            threshold: number;
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Near */
            near: components["schemas"]["RecommendationItem"][];
        };
        /** ScoreDTO */
        ScoreDTO: {
            /** Track */
            track: string;
            /** Passed */
            passed: boolean;
            /** Total Score */
            total_score: number | null;
            /** Sub Scores */
            sub_scores: {
                [key: string]: number;
            } | null;
            /** Buy Low */
            buy_low: number | null;
            /** Buy High */
            buy_high: number | null;
            /** Stop Loss */
            stop_loss: number | null;
            /** Loss Pct */
            loss_pct: number | null;
            /** Reasons */
            reasons: string[] | null;
        };
        /** SectorConstituent */
        SectorConstituent: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Wave Score */
            wave_score: number | null;
            /** Long Score */
            long_score: number | null;
            /** Recommended */
            recommended: boolean;
        };
        /** SectorDetail */
        SectorDetail: {
            sector: components["schemas"]["SectorItem"];
            /** Constituents */
            constituents: components["schemas"]["SectorConstituent"][];
        };
        /** SectorItem */
        SectorItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Strength Score */
            strength_score: number | null;
            /** Dim Momentum */
            dim_momentum: number | null;
            /** Dim Fund */
            dim_fund: number | null;
            /** Dim Tech */
            dim_tech: number | null;
            /** Trend Short */
            trend_short: string | null;
            /** Trend Long */
            trend_long: string | null;
            /** Rotation Stage */
            rotation_stage: string | null;
            /** Momentum 5 */
            momentum_5: number | null;
            /** Momentum 20 */
            momentum_20: number | null;
            /** Foreign Net */
            foreign_net: number | null;
            /** Turnover Share */
            turnover_share: number | null;
            /** Above Ma20 */
            above_ma20: number | null;
            /** Constituents */
            constituents: number | null;
        };
        /** SectorList */
        SectorList: {
            /** Date */
            date: string | null;
            /** Items */
            items: components["schemas"]["SectorItem"][];
        };
        /** StockDetail */
        StockDetail: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Sector Name */
            sector_name: string | null;
            /** Market */
            market: string | null;
            /** Date */
            date: string | null;
            /** Close */
            close: number | null;
            /** Change */
            change: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Scores */
            scores: {
                [key: string]: components["schemas"]["ScoreDTO"] | null;
            };
            chip: components["schemas"]["ChipSummary"] | null;
            fundamental: components["schemas"]["FundamentalSummary"] | null;
        };
        /** TokenBody */
        TokenBody: {
            /** Token */
            token?: string | null;
            /**
             * Save
             * @default false
             */
            save: boolean;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /** Fee */
            fee?: number | null;
            /** Tax */
            tax?: number | null;
            /** Note */
            note?: string | null;
        };
        /** TransactionDTO */
        TransactionDTO: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /** Fee */
            fee: number | null;
            /** Tax */
            tax: number | null;
            /** Note */
            note: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recommendations_recommendations_get: {
        parameters: {
            query?: {
                track?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_detail_stocks__stock_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_ohlcv_stocks__stock_id__ohlcv_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcvResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holdings_holdings_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_holding_holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_transaction_holdings__holding_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_holding_holdings__holding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sectors_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorList"];
                };
            };
        };
    };
    sector_detail_sectors__sector_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    system_status_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sources_health_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    test_source_sources__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_pipeline_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
