/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Search
         * @description 股號/股名查詢（給查詢框跳轉用）。代號前綴或名稱包含皆比對，依相關度排序取前 10。
         */
        get: operations["stock_search_stocks_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calibration
         * @description 分數校準回測結果（波段軌；L4）。讀快取，無則回空殼。重算用 POST /calibration/recompute。
         */
        get: operations["calibration_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibration/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calibration Recompute
         * @description 重跑校準（較重，~分鐘級）。as-of 用最新行情日。
         */
        post: operations["calibration_recompute_calibration_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expectancy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Expectancy
         * @description 逐筆交易期望值回測結果（波段軌）。讀快取，重算用 POST /expectancy/recompute。
         */
        get: operations["expectancy_expectancy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expectancy/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expectancy Recompute
         * @description 重跑逐筆期望值回測（較重，~分鐘級）。
         */
        post: operations["expectancy_recompute_expectancy_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/param-sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Param Sweep
         * @description 出場參數掃描 + walk-forward 結果（波段軌）。讀快取。
         */
        get: operations["param_sweep_param_sweep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/param-sweep/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Param Sweep Recompute
         * @description 重跑參數掃描（最重，~數分鐘）。
         */
        post: operations["param_sweep_recompute_param_sweep_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_stocks__stock_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/ohlcv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Ohlcv */
        get: operations["stock_ohlcv_stocks__stock_id__ohlcv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Levels
         * @description 客觀支撐/壓力位（均線群+波段前低+量價套牢區，純算不靠 LLM）。
         */
        get: operations["stock_levels_stocks__stock_id__levels_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/holding-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Holding History
         * @description 集保大戶/散戶占比週序列（曲線用）。史料不足時背景回補近一年（看哪檔補哪檔）。
         */
        get: operations["holding_history_stocks__stock_id__holding_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/chip-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chip History
         * @description 籌碼每日序列（三大法人買賣超 + 融資融券餘額），供每日買賣量 + 累計曲線。
         */
        get: operations["chip_history_stocks__stock_id__chip_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Holdings */
        get: operations["list_holdings_holdings_get"];
        put?: never;
        /** Create Holding */
        post: operations["create_holding_holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings/{holding_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Transaction */
        post: operations["add_transaction_holdings__holding_id__transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Holding */
        delete: operations["delete_holding_holdings__holding_id__delete"];
        options?: never;
        head?: never;
        /** Patch Holding */
        patch: operations["patch_holding_holdings__holding_id__patch"];
        trace?: never;
    };
    "/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sectors */
        get: operations["list_sectors_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sectors/{sector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sector Detail */
        get: operations["sector_detail_sectors__sector_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intel */
        get: operations["intel_intel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlists */
        get: operations["list_watchlists_watchlists_get"];
        put?: never;
        /** Create Watchlist */
        post: operations["create_watchlist_watchlists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlists/{wl_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist */
        delete: operations["delete_watchlist_watchlists__wl_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlists/{wl_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_watchlists__wl_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_watchlist_items__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist-items/{item_id}/to-holding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Item To Holding */
        post: operations["item_to_holding_watchlist_items__item_id__to_holding_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Settings */
        put: operations["update_settings_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{key}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Settings */
        post: operations["reset_settings_settings__key__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_settings_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Health */
        get: operations["stock_health_stocks__stock_id__health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assistant Chat */
        post: operations["assistant_chat_assistant_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources Health */
        get: operations["sources_health_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Source
         * @description 設定頁[測試連線]：可先測再存（測通才存）。
         */
        post: operations["test_source_sources__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Pipeline
         * @description 設定頁[立即載入]：背景執行，立即回 accepted。已在跑則回 already_running。
         */
        post: operations["trigger_pipeline_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertBrief */
        AlertBrief: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Light */
            light: string;
            /** Return Pct */
            return_pct: number | null;
            /** Signals */
            signals: string[];
        };
        /** Candle */
        Candle: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Volume */
            volume: number | null;
            /** Ma5 */
            ma5?: number | null;
            /** Ma20 */
            ma20?: number | null;
            /** Ma60 */
            ma60?: number | null;
            /** Kd K */
            kd_k?: number | null;
            /** Kd D */
            kd_d?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
        };
        /** ChatMsg */
        ChatMsg: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Context
             * @default {}
             */
            context: {
                [key: string]: unknown;
            };
            /** History */
            history: components["schemas"]["ChatMsg"][];
        };
        /** ChipHistoryResponse */
        ChipHistoryResponse: {
            /** Stock Id */
            stock_id: string;
            /** Points */
            points: components["schemas"]["ChipPoint"][];
        };
        /**
         * ChipPoint
         * @description 籌碼每日一點（法人買賣超 + 融資融券餘額）。
         */
        ChipPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Foreign Net */
            foreign_net?: number | null;
            /** Trust Net */
            trust_net?: number | null;
            /** Dealer Net */
            dealer_net?: number | null;
            /** Total Net */
            total_net?: number | null;
            /** Margin Balance */
            margin_balance?: number | null;
            /** Short Balance */
            short_balance?: number | null;
        };
        /** ChipSummary */
        ChipSummary: {
            /** Date */
            date: string | null;
            /** Foreign Net */
            foreign_net: number | null;
            /** Trust Net */
            trust_net: number | null;
            /** Dealer Net */
            dealer_net: number | null;
            /** Total Net */
            total_net: number | null;
            /** Margin Balance */
            margin_balance: number | null;
            /** Short Balance */
            short_balance: number | null;
            /** Holding Date */
            holding_date?: string | null;
            /** Big Pct */
            big_pct?: number | null;
            /** Over1000 Pct */
            over1000_pct?: number | null;
            /** Small Pct */
            small_pct?: number | null;
            /** Holders */
            holders?: number | null;
            /** Big Trend */
            big_trend?: number | null;
        };
        /**
         * EtfInfo
         * @description ETF 身分資料（個股無月營收/本益比時改顯示這塊）。
         */
        EtfInfo: {
            /** Kind */
            kind?: string | null;
            /** Fund Type */
            fund_type?: string | null;
            /** Track Index */
            track_index?: string | null;
            /** Has Foreign */
            has_foreign?: boolean | null;
            /** Scale Label */
            scale_label?: string | null;
            /** Scale Billion */
            scale_billion?: number | null;
            /** Listed Date */
            listed_date?: string | null;
        };
        /** EventBrief */
        EventBrief: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Category */
            category: string | null;
            /** Title */
            title: string;
            /** Is Risk */
            is_risk: boolean;
        };
        /** EventDTO */
        EventDTO: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Category */
            category: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string | null;
            /** Is Risk */
            is_risk: boolean;
            /** Source */
            source: string | null;
            /** Url */
            url: string | null;
        };
        /** FundamentalSummary */
        FundamentalSummary: {
            /** Pe */
            pe?: number | null;
            /** Pb */
            pb?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Eps */
            eps?: number | null;
            /** Revenue Yoy */
            revenue_yoy?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingCreate */
        HoldingCreate: {
            /** Stock Id */
            stock_id: string;
            /** Track */
            track: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /** Fee */
            fee?: number | null;
            /** Stop Loss Override */
            stop_loss_override?: number | null;
            /** Trail Trigger Override */
            trail_trigger_override?: number | null;
            /** Trail Pullback Override */
            trail_pullback_override?: number | null;
            /** Note */
            note?: string | null;
        };
        /** HoldingHistoryResponse */
        HoldingHistoryResponse: {
            /** Stock Id */
            stock_id: string;
            /** Points */
            points: components["schemas"]["HoldingPoint"][];
            /** Backfilling */
            backfilling: boolean;
        };
        /** HoldingItem */
        HoldingItem: {
            /** Id */
            id: number;
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Track */
            track: string;
            /** Status */
            status: string;
            /** Opened Date */
            opened_date: string | null;
            /** Closed Date */
            closed_date: string | null;
            /** Shares */
            shares: number;
            /** Avg Cost */
            avg_cost: number | null;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Market Value */
            market_value: number | null;
            /** Unrealized Pnl */
            unrealized_pnl: number | null;
            /** Return Pct */
            return_pct: number | null;
            /** Realized Pnl */
            realized_pnl: number | null;
            /** Light */
            light: string;
            /** Level */
            level: string;
            /** Signals */
            signals: string[];
            /** Hard Stop */
            hard_stop: number | null;
            /** Highest */
            highest: number | null;
            /** Drawdown Pct */
            drawdown_pct: number | null;
            /** Trail Active */
            trail_active: boolean;
            /** Stop Loss Override */
            stop_loss_override: number | null;
            /** Trail Trigger Override */
            trail_trigger_override: number | null;
            /** Trail Pullback Override */
            trail_pullback_override: number | null;
            /** Note */
            note: string | null;
            /** Transactions */
            transactions: components["schemas"]["TransactionDTO"][];
        };
        /** HoldingPatch */
        HoldingPatch: {
            /** Stop Loss Override */
            stop_loss_override?: number | null;
            /** Trail Trigger Override */
            trail_trigger_override?: number | null;
            /** Trail Pullback Override */
            trail_pullback_override?: number | null;
            /** Note */
            note?: string | null;
        };
        /**
         * HoldingPoint
         * @description 集保週資料單點（曲線用）。
         */
        HoldingPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Big Pct */
            big_pct?: number | null;
            /** Over1000 Pct */
            over1000_pct?: number | null;
            /** Small Pct */
            small_pct?: number | null;
            /** Holders */
            holders?: number | null;
        };
        /** HoldingsResponse */
        HoldingsResponse: {
            /** Status */
            status: string;
            /** Items */
            items: components["schemas"]["HoldingItem"][];
            summary: components["schemas"]["HoldingsSummary"];
        };
        /** HoldingsSummary */
        HoldingsSummary: {
            /** Count */
            count: number;
            /** Total Market Value */
            total_market_value: number;
            /** Total Unrealized Pnl */
            total_unrealized_pnl: number;
            /** Total Return Pct */
            total_return_pct: number | null;
            /** Total Realized Pnl */
            total_realized_pnl: number;
        };
        /** IntelEvent */
        IntelEvent: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Category */
            category: string | null;
            /** Title */
            title: string;
            /** Is Risk */
            is_risk: boolean;
            /** Source */
            source: string | null;
            /** Url */
            url: string | null;
        };
        /** IntelResponse */
        IntelResponse: {
            /** Date */
            date: string | null;
            /** Market Digest */
            market_digest?: string | null;
            /** Focus Digest */
            focus_digest?: string | null;
            /** Themes */
            themes: components["schemas"]["ThemeDigest"][];
            /** Events */
            events: components["schemas"]["IntelEvent"][];
            /** Total */
            total: number;
            /** Risk Count */
            risk_count: number;
            /** Has Digest */
            has_digest: boolean;
        };
        /** LevelDTO */
        LevelDTO: {
            /** Price */
            price: number;
            /** Kind */
            kind: string;
            /** Strength */
            strength: number;
            /** Methods */
            methods: string[];
            /** Distance Pct */
            distance_pct: number;
        };
        /** LevelsResponse */
        LevelsResponse: {
            /** Stock Id */
            stock_id: string;
            /** Close */
            close: number | null;
            /** Supports */
            supports: components["schemas"]["LevelDTO"][];
            /** Resistances */
            resistances: components["schemas"]["LevelDTO"][];
        };
        /** MarketSummary */
        MarketSummary: {
            /** Date */
            date: string | null;
            /** Turnover Billion */
            turnover_billion: number | null;
            /** Advancers */
            advancers: number;
            /** Decliners */
            decliners: number;
            /** Unchanged */
            unchanged: number;
            /** Foreign Net */
            foreign_net: number | null;
            /** Trust Net */
            trust_net: number | null;
            /** Dealer Net */
            dealer_net: number | null;
            /** Pct Above Ma20 */
            pct_above_ma20?: number | null;
            /** Pct Above Ma60 */
            pct_above_ma60?: number | null;
            /** Foreign Buy Count */
            foreign_buy_count?: number | null;
            /** Foreign Sell Count */
            foreign_sell_count?: number | null;
            /** Trust Buy Count */
            trust_buy_count?: number | null;
            /** Trust Sell Count */
            trust_sell_count?: number | null;
            /** Trust Top10 Concentration */
            trust_top10_concentration?: number | null;
        };
        /** OhlcvResponse */
        OhlcvResponse: {
            /** Stock Id */
            stock_id: string;
            /** Candles */
            candles: components["schemas"]["Candle"][];
        };
        /** OverviewResponse */
        OverviewResponse: {
            market: components["schemas"]["MarketSummary"];
            /** Market Note */
            market_note?: string | null;
            /** Holdings Alerts */
            holdings_alerts: components["schemas"]["AlertBrief"][];
            /** Reco Wave Count */
            reco_wave_count: number;
            /** Reco Long Count */
            reco_long_count: number;
            /** Reco Top */
            reco_top: components["schemas"]["RecoBrief"][];
            /** Sectors Top */
            sectors_top: components["schemas"]["SectorBrief"][];
            /** Recent Events */
            recent_events: components["schemas"]["EventBrief"][];
        };
        /** RecoBrief */
        RecoBrief: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Track */
            track: string;
            /** Total Score */
            total_score: number | null;
        };
        /**
         * RecommendationDetail
         * @description 展開區單一面向：分數 + 帶數字的客觀證據（波段軌目前有 evidence；長線軌暫無）。
         */
        RecommendationDetail: {
            /** Category */
            category: string;
            /** Score */
            score: number;
            /** Evidence */
            evidence?: string | null;
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Sector Name */
            sector_name: string | null;
            /** Track */
            track: string;
            /** Total Score */
            total_score: number | null;
            /** Sub Scores */
            sub_scores: {
                [key: string]: number;
            } | null;
            /** Coverage */
            coverage: number | null;
            /** Confidence */
            confidence: number | null;
            /** Stability */
            stability: number | null;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Buy Low */
            buy_low: number | null;
            /** Buy High */
            buy_high: number | null;
            /** Stop Loss */
            stop_loss: number | null;
            /** Loss Pct */
            loss_pct: number | null;
            /** Reasons */
            reasons: string[] | null;
            /** Details */
            details?: components["schemas"]["RecommendationDetail"][] | null;
            /** Spark */
            spark?: number[] | null;
        };
        /** RecommendationList */
        RecommendationList: {
            /** Track */
            track: string;
            /** Style */
            style?: string | null;
            /** Date */
            date: string | null;
            /** Threshold */
            threshold: number;
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Near */
            near: components["schemas"]["RecommendationItem"][];
        };
        /** ScoreDTO */
        ScoreDTO: {
            /** Track */
            track: string;
            /** Passed */
            passed: boolean;
            /** Total Score */
            total_score: number | null;
            /** Sub Scores */
            sub_scores: {
                [key: string]: number;
            } | null;
            /** Coverage */
            coverage: number | null;
            /** Confidence */
            confidence: number | null;
            /** Stability */
            stability: number | null;
            /** Buy Low */
            buy_low: number | null;
            /** Buy High */
            buy_high: number | null;
            /** Stop Loss */
            stop_loss: number | null;
            /** Loss Pct */
            loss_pct: number | null;
            /** Reasons */
            reasons: string[] | null;
            /** Details */
            details?: components["schemas"]["RecommendationDetail"][] | null;
        };
        /** SectorBrief */
        SectorBrief: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Strength Score */
            strength_score: number | null;
            /** Trend Short */
            trend_short: string | null;
            /** Rotation Stage */
            rotation_stage: string | null;
        };
        /** SectorConstituent */
        SectorConstituent: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Wave Score */
            wave_score: number | null;
            /** Long Score */
            long_score: number | null;
            /** Recommended */
            recommended: boolean;
        };
        /** SectorDetail */
        SectorDetail: {
            sector: components["schemas"]["SectorItem"];
            /** Constituents */
            constituents: components["schemas"]["SectorConstituent"][];
            /** Interpretation */
            interpretation?: string | null;
        };
        /** SectorItem */
        SectorItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Strength Score */
            strength_score: number | null;
            /** Dim Momentum */
            dim_momentum: number | null;
            /** Dim Fund */
            dim_fund: number | null;
            /** Dim Tech */
            dim_tech: number | null;
            /** Trend Short */
            trend_short: string | null;
            /** Trend Long */
            trend_long: string | null;
            /** Rotation Stage */
            rotation_stage: string | null;
            /** Momentum 5 */
            momentum_5: number | null;
            /** Momentum 20 */
            momentum_20: number | null;
            /** Foreign Net */
            foreign_net: number | null;
            /** Turnover Share */
            turnover_share: number | null;
            /** Above Ma20 */
            above_ma20: number | null;
            /** Constituents */
            constituents: number | null;
        };
        /** SectorList */
        SectorList: {
            /** Date */
            date: string | null;
            /** Items */
            items: components["schemas"]["SectorItem"][];
        };
        /** StockDetail */
        StockDetail: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Sector Name */
            sector_name: string | null;
            /** Market */
            market: string | null;
            /** Date */
            date: string | null;
            /** Close */
            close: number | null;
            /** Change */
            change: number | null;
            /** Change Pct */
            change_pct: number | null;
            /**
             * Is Etf
             * @default false
             */
            is_etf: boolean;
            /** Scores */
            scores: {
                [key: string]: components["schemas"]["ScoreDTO"] | null;
            };
            chip: components["schemas"]["ChipSummary"] | null;
            fundamental: components["schemas"]["FundamentalSummary"] | null;
            etf?: components["schemas"]["EtfInfo"] | null;
            /** Events */
            events: components["schemas"]["EventDTO"][];
            /** News Digest */
            news_digest?: string | null;
        };
        /**
         * StockSearchItem
         * @description 查詢框結果項（股號/股名跳轉用）。
         */
        StockSearchItem: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Market */
            market?: string | null;
            /**
             * Is Etf
             * @default false
             */
            is_etf: boolean;
        };
        /** ThemeDigest */
        ThemeDigest: {
            /** Sector Id */
            sector_id: number;
            /** Sector Name */
            sector_name: string;
            /** Digest */
            digest: string;
            /** Event Count */
            event_count: number;
            /** Risk Count */
            risk_count: number;
        };
        /** ToHolding */
        ToHolding: {
            /** Track */
            track: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
        };
        /** TokenBody */
        TokenBody: {
            /** Token */
            token?: string | null;
            /**
             * Save
             * @default false
             */
            save: boolean;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /** Fee */
            fee?: number | null;
            /** Tax */
            tax?: number | null;
            /** Note */
            note?: string | null;
        };
        /** TransactionDTO */
        TransactionDTO: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
            /** Fee */
            fee: number | null;
            /** Tax */
            tax: number | null;
            /** Note */
            note: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistCreate */
        WatchlistCreate: {
            /** Name */
            name: string;
        };
        /** WatchlistDTO */
        WatchlistDTO: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["WatchlistItemDTO"][];
        };
        /** WatchlistItemCreate */
        WatchlistItemCreate: {
            /** Stock Id */
            stock_id: string;
            /** Target Price */
            target_price?: number | null;
            /** Added Price */
            added_price?: number | null;
            /** Added Date */
            added_date?: string | null;
            /** Reason */
            reason?: string | null;
            /** Note */
            note?: string | null;
        };
        /** WatchlistItemDTO */
        WatchlistItemDTO: {
            /** Id */
            id: number;
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Added Price */
            added_price: number | null;
            /** Target Price */
            target_price: number | null;
            /** Added Date */
            added_date: string | null;
            /** Reason */
            reason: string | null;
            /** Note */
            note: string | null;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Wave Score */
            wave_score: number | null;
            /** Long Score */
            long_score: number | null;
            /** Light */
            light: string;
            /** Reminders */
            reminders: string[];
        };
        /** WatchlistsResponse */
        WatchlistsResponse: {
            /** Watchlists */
            watchlists: components["schemas"]["WatchlistDTO"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recommendations_recommendations_get: {
        parameters: {
            query?: {
                track?: string;
                style?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_search_stocks_search_get: {
        parameters: {
            query: {
                /** @description 股號或股名關鍵字 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockSearchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibration_calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    calibration_recompute_calibration_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    expectancy_expectancy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    expectancy_recompute_expectancy_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    param_sweep_param_sweep_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    param_sweep_recompute_param_sweep_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stock_detail_stocks__stock_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_ohlcv_stocks__stock_id__ohlcv_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcvResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_levels_stocks__stock_id__levels_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LevelsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holding_history_stocks__stock_id__holding_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chip_history_stocks__stock_id__chip_history_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChipHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_holdings_holdings_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_holding_holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_transaction_holdings__holding_id__transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_holding_holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_holding_holdings__holding_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                holding_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sectors_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorList"];
                };
            };
        };
    };
    sector_detail_sectors__sector_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sector_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    intel_intel_get: {
        parameters: {
            query?: {
                days?: number;
                category?: string | null;
                risk_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlists_watchlists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistsResponse"];
                };
            };
        };
    };
    create_watchlist_watchlists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_watchlists__wl_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wl_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_item_watchlists__wl_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wl_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_item_watchlist_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    item_to_holding_watchlist_items__item_id__to_holding_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToHolding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    update_settings_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_settings_settings__key__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recompute_settings_recompute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stock_health_stocks__stock_id__health_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assistant_chat_assistant_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    system_status_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sources_health_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    test_source_sources__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_pipeline_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
