/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Detail */
        get: operations["stock_detail_stocks__stock_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{stock_id}/ohlcv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Ohlcv */
        get: operations["stock_ohlcv_stocks__stock_id__ohlcv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources Health */
        get: operations["sources_health_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{name}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Source
         * @description 設定頁[測試連線]：可先測再存（測通才存）。
         */
        post: operations["test_source_sources__name__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Pipeline
         * @description 手動重跑（設定頁 / 補跑）。背景執行，立即回 accepted。
         */
        post: operations["trigger_pipeline_pipeline_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candle */
        Candle: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Volume */
            volume: number | null;
            /** Ma5 */
            ma5?: number | null;
            /** Ma20 */
            ma20?: number | null;
            /** Ma60 */
            ma60?: number | null;
            /** Kd K */
            kd_k?: number | null;
            /** Kd D */
            kd_d?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
        };
        /** ChipSummary */
        ChipSummary: {
            /** Date */
            date: string | null;
            /** Foreign Net */
            foreign_net: number | null;
            /** Trust Net */
            trust_net: number | null;
            /** Dealer Net */
            dealer_net: number | null;
            /** Total Net */
            total_net: number | null;
            /** Margin Balance */
            margin_balance: number | null;
            /** Short Balance */
            short_balance: number | null;
        };
        /** FundamentalSummary */
        FundamentalSummary: {
            /** Pe */
            pe?: number | null;
            /** Pb */
            pb?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Eps */
            eps?: number | null;
            /** Revenue Yoy */
            revenue_yoy?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OhlcvResponse */
        OhlcvResponse: {
            /** Stock Id */
            stock_id: string;
            /** Candles */
            candles: components["schemas"]["Candle"][];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Sector Name */
            sector_name: string | null;
            /** Track */
            track: string;
            /** Total Score */
            total_score: number | null;
            /** Sub Scores */
            sub_scores: {
                [key: string]: number;
            } | null;
            /** Close */
            close: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Buy Low */
            buy_low: number | null;
            /** Buy High */
            buy_high: number | null;
            /** Stop Loss */
            stop_loss: number | null;
            /** Loss Pct */
            loss_pct: number | null;
            /** Reasons */
            reasons: string[] | null;
        };
        /** RecommendationList */
        RecommendationList: {
            /** Track */
            track: string;
            /** Date */
            date: string | null;
            /** Threshold */
            threshold: number;
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Near */
            near: components["schemas"]["RecommendationItem"][];
        };
        /** ScoreDTO */
        ScoreDTO: {
            /** Track */
            track: string;
            /** Passed */
            passed: boolean;
            /** Total Score */
            total_score: number | null;
            /** Sub Scores */
            sub_scores: {
                [key: string]: number;
            } | null;
            /** Buy Low */
            buy_low: number | null;
            /** Buy High */
            buy_high: number | null;
            /** Stop Loss */
            stop_loss: number | null;
            /** Loss Pct */
            loss_pct: number | null;
            /** Reasons */
            reasons: string[] | null;
        };
        /** StockDetail */
        StockDetail: {
            /** Stock Id */
            stock_id: string;
            /** Name */
            name: string;
            /** Sector Name */
            sector_name: string | null;
            /** Market */
            market: string | null;
            /** Date */
            date: string | null;
            /** Close */
            close: number | null;
            /** Change */
            change: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Scores */
            scores: {
                [key: string]: components["schemas"]["ScoreDTO"] | null;
            };
            chip: components["schemas"]["ChipSummary"] | null;
            fundamental: components["schemas"]["FundamentalSummary"] | null;
        };
        /** TokenBody */
        TokenBody: {
            /** Token */
            token?: string | null;
            /**
             * Save
             * @default false
             */
            save: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    recommendations_recommendations_get: {
        parameters: {
            query?: {
                track?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_detail_stocks__stock_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_ohlcv_stocks__stock_id__ohlcv_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                stock_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OhlcvResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    system_status_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sources_health_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    test_source_sources__name__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_pipeline_pipeline_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
